"""
Define the universe of stocks to scan
"""

# NIFTY 50 Symbols
NIFTY_50 = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK",
    "HINDUNILVR", "SBIN", "BHARTIARTL", "ITC", "KOTAKBANK",
    "LT", "HCLTECH", "AXISBANK", "ASIANPAINT", "MARUTI",
    "SUNPHARMA", "TITAN", "BAJFINANCE", "WIPRO", "ULTRACEMCO",
    "NESTLEIND", "NTPC", "TATAMOTORS", "M&M", "POWERGRID",
    "TECHM", "ADANIENT", "ADANIPORTS", "BAJAJFINSV", "COALINDIA",
    "GRASIM", "CIPLA", "JSWSTEEL", "ONGC", "TATASTEEL",
    "HINDALCO", "DRREDDY", "EICHERMOT", "DIVISLAB", "BPCL",
    "BRITANNIA", "APOLLOHOSP", "INDUSINDBK", "TATACONSUM", "SBILIFE",
    "HDFCLIFE", "HEROMOTOCO", "BAJAJ-AUTO", "UPL", "LTIM"
]

# NIFTY NEXT 50
NIFTY_NEXT_50 = [
    "ADANIGREEN", "AMBUJACEM", "BANKBARODA", "BEL", "BERGEPAINT",
    "CANBK", "CHOLAFIN", "COLPAL", "DLF", "GAIL",
    "GODREJCP", "HAVELLS", "ICICIGI", "ICICIPRULI", "IDEA",
    "IGL", "INDUSTOWER", "IOC", "IRCTC", "JINDALSTEL",
    # ... add more
]

# NIFTY 500 or Full NSE List
# Can be fetched dynamically

# Sector-wise grouping
SECTORS = {
    "IT": ["TCS", "INFY", "WIPRO", "HCLTECH", "TECHM", "LTIM"],
    "BANKING": ["HDFCBANK", "ICICIBANK", "SBIN", "KOTAKBANK", "AXISBANK", "INDUSINDBK"],
    "PHARMA": ["SUNPHARMA", "DRREDDY", "CIPLA", "DIVISLAB", "APOLLOHOSP"],
    "AUTO": ["MARUTI", "TATAMOTORS", "M&M", "EICHERMOT", "BAJAJ-AUTO", "HEROMOTOCO"],
    "FMCG": ["HINDUNILVR", "ITC", "NESTLEIND", "BRITANNIA", "TATACONSUM", "COLPAL"],
    "ENERGY": ["RELIANCE", "NTPC", "POWERGRID", "ONGC", "BPCL", "COALINDIA"],
    "METALS": ["TATASTEEL", "JSWSTEEL", "HINDALCO", "JINDALSTEL"],
    "FINANCE": ["BAJFINANCE", "BAJAJFINSV", "CHOLAFIN", "SBILIFE", "HDFCLIFE"],
    "REALTY": ["DLF"],
    "INFRA": ["LT", "ADANIENT", "ADANIPORTS"],
}

# Index tracking
INDICES = {
    "NIFTY50": "^NSEI",
    "BANKNIFTY": "^NSEBANK",
    "NIFTYIT": "^CNXIT",
    "SENSEX": "^BSESN",
    "NIFTYMIDCAP": "NIFTY_MID_SELECT.NS",
}
